[build]
  # Perintah untuk menginstall semua dependensi Python
  command = "pip install -r requirements.txt"

  # Direktori tempat fungsi serverless akan ditempatkan oleh Netlify
  functions = "netlify/functions/"

  # Direktori untuk file statis (CSS, JS, gambar)
  publish = "static/"

[functions]
  # Memastikan folder 'model' dan 'templates' disertakan dalam build fungsi
  included_files = ["model/**", "templates/**"]

[[redirects]]
  # Mengalihkan semua permintaan masuk ke fungsi serverless 'app'
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
